name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Development Environment
      run : sudo apt update && sudo apt install mingw-w64
      
    - name: Install meson
      run : sudo apt-get install meson

    - name: Install nasm
      run : sudo apt install nasm  
      
    - name: Build
      run: ./build.sh
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: harmonic.zip
