name: CI Build

on: push

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        shell: arch -x86_64 zsh -e {0}
    steps:
     - name: Setup x86 Development Environment
       run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

     - name: Install Development Environment
       run : /usr/local/bin/brew install ninja meson cmake  nasm  mingw-w64

     - name: build
       run : sh build.sh
       
     - name: Upload
       uses: actions/upload-artifact@v4
       with:
          name: artifacts
          path: harmonic.zip

          
